export const COUNTRIES = [
  { label: 'United States', value: 'US', dialCode: '+1' },
  { label: 'United Kingdom', value: 'GB', dialCode: '+44' },
  { label: 'Canada', value: 'CA', dialCode: '+1' },
  { label: 'Australia', value: 'AU', dialCode: '+61' },
  { label: 'Germany', value: 'DE', dialCode: '+49' },
  { label: 'France', value: 'FR', dialCode: '+33' },
  { label: 'India', value: 'IN', dialCode: '+91' },
  { label: 'Japan', value: 'JP', dialCode: '+81' },
  { label: 'China', value: 'CN', dialCode: '+86' },
  { label: 'Brazil', value: 'BR', dialCode: '+55' },
  { label: 'Mexico', value: 'MX', dialCode: '+52' },
  { label: 'Italy', value: 'IT', dialCode: '+39' },
  { label: 'Spain', value: 'ES', dialCode: '+34' },
  { label: 'Netherlands', value: 'NL', dialCode: '+31' },
  { label: 'Sweden', value: 'SE', dialCode: '+46' },
  { label: 'Switzerland', value: 'CH', dialCode: '+41' },
  { label: 'South Korea', value: 'KR', dialCode: '+82' },
  { label: 'Singapore', value: 'SG', dialCode: '+65' },
  { label: 'New Zealand', value: 'NZ', dialCode: '+64' },
  { label: 'Ireland', value: 'IE', dialCode: '+353' },
];
